schema {
	query: queryType
}
type queryType {
	maybeNull: Int
	small: Small
	manysmall: [Small!]!
	name: String!
	neverNull: Int!
	foo: Int!
	bar: Int!
}
type Small {
	name: String!
	arg(a: Int!): [SmallChild!]!
	id: Int!
	foobar: [SmallChild!]!
}
type SmallChild {
	foo(a: Int!): Int!
	id: Int!
	name: String!
}
