schema {
	mutation: mutationType
	query: queryType
	subscription: subscriptionType
}
type mutationType { _: Boolean }
type queryType {
	maybeNull: Int
	small: Small
	manysmall: [Small!]!
	neverNull: Int!
	foo: Int!
	bar: Int!
}
type subscriptionType { _: Boolean }
type Small {
	id: Int!
	name: String!
	foobar: [SmallChild!]!
	arg(a: Int!): [SmallChild!]!
}
input SmallIn {
	id: Int!
	name: String!
	foobar: [SmallChildIn!]!
}
type SmallChild {
	id: Int!
	name: String!
	foo(a: Int!): Int!
}
input SmallChildIn {
	id: Int!
	name: String!
}
