schema {
	mutation: mutationType
	query: queryType
	subscription: subscriptionType
}
type mutationType { _: Boolean }
type queryType {
	foo: Int
	manysmall: [Small]
	bar: Int
	small: Small
}
type subscriptionType { _: Boolean }
type Small {
	id: Int
	foobar: [SmallChild]
	name: String
	arg(a: Int): [SmallChild]
}
input SmallIn {
	id: Int
	foobar: [SmallChildIn]
	name: String
}
type SmallChild {
	id: Int
	name: String
	foo(a: Int): Int
}
input SmallChildIn {
	id: Int
	name: String
}
